//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWorksheet.Website.Server.Shared.Locale.ServerResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWorksheet.Website.Server.Shared.Locale.ServerResources.ServerResources", typeof(ServerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_ChangePassword_Mismatch {
            get {
                return ResourceManager.GetString("Account/ChangePassword.Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_ChangePassword_OldPasswordMismatch {
            get {
                return ResourceManager.GetString("Account/ChangePassword.OldPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_ChangePassword_YouAreTestUser {
            get {
                return ResourceManager.GetString("Account/ChangePassword.YouAreTestUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_PasswordReset_DefaultText {
            get {
                return ResourceManager.GetString("Account/PasswordReset.DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_ResetPassword_InactiveAccount {
            get {
                return ResourceManager.GetString("Account/ResetPassword.InactiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Account_ResetPassword_InvalidToken {
            get {
                return ResourceManager.GetString("Account/ResetPassword.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_Create_LimitReached {
            get {
                return ResourceManager.GetString("AccountAssosiation/Create.LimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_Redeem_Code {
            get {
                return ResourceManager.GetString("AccountAssosiation/Redeem.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_RemoveAdminstrator_NoActive {
            get {
                return ResourceManager.GetString("AccountAssosiation/RemoveAdminstrator.NoActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_TryRedeem_AssosiationExists {
            get {
                return ResourceManager.GetString("AccountAssosiation/TryRedeem.AssosiationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_TryRedeem_Expired {
            get {
                return ResourceManager.GetString("AccountAssosiation/TryRedeem.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_TryRedeem_Expired2 {
            get {
                return ResourceManager.GetString("AccountAssosiation/TryRedeem.Expired2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_TryRedeem_Pun {
            get {
                return ResourceManager.GetString("AccountAssosiation/TryRedeem.Pun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AccountAssosiation_TryRedeem_Unkown {
            get {
                return ResourceManager.GetString("AccountAssosiation/TryRedeem.Unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Common_GoogleVertficationFailed {
            get {
                return ResourceManager.GetString("Common/GoogleVertficationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Common_InvalidId {
            get {
                return ResourceManager.GetString("Common/InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Common_SecureStringHint {
            get {
                return ResourceManager.GetString("Common/SecureStringHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Entity_ProjectItemRate {
            get {
                return ResourceManager.GetString("Entity/ProjectItemRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Login_MaxTrys {
            get {
                return ResourceManager.GetString("Login/MaxTrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Org_NotPartOfOrg {
            get {
                return ResourceManager.GetString("Org/NotPartOfOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ProjectItemRate_Delete_RateInUse {
            get {
                return ResourceManager.GetString("ProjectItemRate/Delete.RateInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Register_Disabled {
            get {
                return ResourceManager.GetString("Register/Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Register_Done {
            get {
                return ResourceManager.GetString("Register.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Register_MailFailed {
            get {
                return ResourceManager.GetString("Register/MailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Register_UnexpectedError {
            get {
                return ResourceManager.GetString("Register/UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Report_Names_Worksheet {
            get {
                return ResourceManager.GetString("Report/Names.Worksheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_DataTemplate_Comment_DataSource {
            get {
                return ResourceManager.GetString("Reporting/DataTemplate.Comment.DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_FullProject_Arguments_Name_Project {
            get {
                return ResourceManager.GetString("Reporting/FullProject.Arguments.Name.Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_Aggregations_CalculatedNet {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.Aggregations.CalculatedNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_Aggregations_CalculatedTax {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.Aggregations.CalculatedTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_Aggregations_WorkedMinutes {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.Aggregations.WorkedMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_AssertInfos {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.AssertInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_AssertInfos_TotalTax {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.AssertInfos.TotalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_AssertInfos_TotalValue {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.AssertInfos.TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_CommonInfos {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.CommonInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_Creator {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_Owner {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Comment_WorktimeInfos {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Comment.WorktimeInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Form_Comment_AdditionalInfos {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Form.Comment.AdditionalInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Form_Comment_Date {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Form.Comment.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Form_Comment_InvoiceNo {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Form.Comment.InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Form_Comment_PaymentInfos {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Form.Comment.PaymentInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Form_Comment_Project {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Form.Comment.Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Form_Comment_RoundBy {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Form.Comment.RoundBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_Form_Comment_UseParentOrgAsAddress {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.Form.Comment.UseParentOrgAsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Reporting_ProjectSpec_WorksheetRates {
            get {
                return ResourceManager.GetString("Reporting/ProjectSpec.WorksheetRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Role_AddRole_UserHasRole {
            get {
                return ResourceManager.GetString("Role/AddRole.UserHasRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Role_RemoveRole_SuperAdmin {
            get {
                return ResourceManager.GetString("Role/RemoveRole.SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Statistics_ActionCases_Arguments_Comments_FromDate {
            get {
                return ResourceManager.GetString("Statistics/ActionCases.Arguments.Comments.FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Statistics_ActionCases_Arguments_Comments_IncludenNonSub {
            get {
                return ResourceManager.GetString("Statistics/ActionCases.Arguments.Comments.IncludenNonSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Statistics_ActionCases_Arguments_Comments_ToDate {
            get {
                return ResourceManager.GetString("Statistics/ActionCases.Arguments.Comments.ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Statistics_ActionCases_Arguments_Names_FromDate {
            get {
                return ResourceManager.GetString("Statistics/ActionCases.Arguments.Names.FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Statistics_ActionCases_Arguments_Names_IncludeNonSub {
            get {
                return ResourceManager.GetString("Statistics/ActionCases.Arguments.Names.IncludeNonSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Statistics_ActionCases_Arguments_Names_ToDate {
            get {
                return ResourceManager.GetString("Statistics/ActionCases.Arguments.Names.ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureBlob_Arguments_Comments_AccountKey {
            get {
                return ResourceManager.GetString("Storage/AzureBlob.Arguments.Comments.AccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureBlob_Arguments_Comments_AccountName {
            get {
                return ResourceManager.GetString("Storage/AzureBlob.Arguments.Comments.AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureBlob_Arguments_Comments_Container {
            get {
                return ResourceManager.GetString("Storage/AzureBlob.Arguments.Comments.Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureBlob_Arguments_Names_AccountKey {
            get {
                return ResourceManager.GetString("Storage/AzureBlob.Arguments.Names.AccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureBlob_Arguments_Names_AccountName {
            get {
                return ResourceManager.GetString("Storage/AzureBlob.Arguments.Names.AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureBlob_Arguments_Names_Container {
            get {
                return ResourceManager.GetString("Storage/AzureBlob.Arguments.Names.Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureFile_Arguments_Comments_Directory {
            get {
                return ResourceManager.GetString("Storage/AzureFile.Arguments.Comments.Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureFile_Arguments_Comments_Share {
            get {
                return ResourceManager.GetString("Storage/AzureFile.Arguments.Comments.Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_AzureFile_Arguments_Names_Directory {
            get {
                return ResourceManager.GetString("Storage/AzureFile.Arguments.Names.Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_FTP_Arguments_Comments_Password {
            get {
                return ResourceManager.GetString("Storage/FTP.Arguments.Comments.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_FTP_Arguments_Comments_Url {
            get {
                return ResourceManager.GetString("Storage/FTP.Arguments.Comments.Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_FTP_Arguments_Names_Url {
            get {
                return ResourceManager.GetString("Storage/FTP.Arguments.Names.Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_Http_Arguments_Comments_BaseUrl {
            get {
                return ResourceManager.GetString("Storage/Http.Arguments.Comments.BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_Http_Arguments_Comments_DeleteUrl {
            get {
                return ResourceManager.GetString("Storage/Http.Arguments.Comments.DeleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_Http_Arguments_Comments_GetUrl {
            get {
                return ResourceManager.GetString("Storage/Http.Arguments.Comments.GetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Storage_Http_Arguments_Comments_PostUrl {
            get {
                return ResourceManager.GetString("Storage/Http.Arguments.Comments.PostUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserWorkload_Errors_KindExists {
            get {
                return ResourceManager.GetString("UserWorkload/Errors.KindExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WebhookData_Comment_Content {
            get {
                return ResourceManager.GetString("WebhookData/Comment.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WebhookData_Comment_CreatedAt {
            get {
                return ResourceManager.GetString("WebhookData/Comment.CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WebhookData_Comment_SendAt {
            get {
                return ResourceManager.GetString("WebhookData/Comment.SendAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WebhookData_Comment_Type {
            get {
                return ResourceManager.GetString("WebhookData/Comment.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WebhookData_Comment_User {
            get {
                return ResourceManager.GetString("WebhookData/Comment.User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Mail_Arguments_Comments_AwaitingResponse {
            get {
                return ResourceManager.GetString("Workflow.Mail/Arguments.Comments.AwaitingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Mail_Arguments_Comments_MailAccount {
            get {
                return ResourceManager.GetString("Workflow.Mail/Arguments.Comments.MailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Mail_Arguments_Comments_Storage {
            get {
                return ResourceManager.GetString("Workflow.Mail/Arguments.Comments.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Mail_Arguments_Names_AwaitingResponse {
            get {
                return ResourceManager.GetString("Workflow.Mail/Arguments.Names.AwaitingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Mail_Arguments_Names_MailAccount {
            get {
                return ResourceManager.GetString("Workflow.Mail/Arguments.Names.MailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Mail_Arguments_Names_Storage {
            get {
                return ResourceManager.GetString("Workflow.Mail/Arguments.Names.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Comments_ConfirmedReport {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Comments.ConfirmedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Comments_CreateReport {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Comments.CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Comments_Report_Storage {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Comments.Report.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Comments_Report_Template {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Comments.Report.Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Comments_SubmitReport {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Comments.SubmitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Names_ConfirmedReport {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Names.ConfirmedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Names_CreateReport {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Names.CreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Names_Report_Storage {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Names.Report.Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Names_Report_Template {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Names.Report.Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Arguments_Names_SubmitReport {
            get {
                return ResourceManager.GetString("Workflow.Manual/Arguments.Names.SubmitReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Data_Comments_ReportData {
            get {
                return ResourceManager.GetString("Workflow.Manual/Data.Comments.ReportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_AwaitingPayment {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.AwaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_AwaitingResponse {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.AwaitingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_Confirmed {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_Created {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_Invalid {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_Payed {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.Payed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_Rejected {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_StatusType_Submitted {
            get {
                return ResourceManager.GetString("Workflow.Manual/StatusType.Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Step_Submit_Arguments_Comments_Description {
            get {
                return ResourceManager.GetString("Workflow.Manual/Step.Submit.Arguments.Comments.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Manual_Step_Submit_Arguments_Names_Description {
            get {
                return ResourceManager.GetString("Workflow.Manual/Step.Submit.Arguments.Names.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Templated_Arguments_Names_AwaitingPayment {
            get {
                return ResourceManager.GetString("Workflow.Templated/Arguments.Names.AwaitingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Templated_Arguments_Names_AwaitingResponse {
            get {
                return ResourceManager.GetString("Workflow.Templated/Arguments.Names.AwaitingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Templated_Arguments_Names_Confirmed {
            get {
                return ResourceManager.GetString("Workflow.Templated/Arguments.Names.Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Templated_Arguments_Names_Created {
            get {
                return ResourceManager.GetString("Workflow.Templated/Arguments.Names.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Workflow_Templated_Arguments_Names_Submitted {
            get {
                return ResourceManager.GetString("Workflow.Templated/Arguments.Names.Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Worksheet_Manual_Steps_Confirmed_Arguments_Comments_InvoiceNo {
            get {
                return ResourceManager.GetString("Worksheet.Manual/Steps.Confirmed.Arguments.Comments.InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Worksheet_Manual_Steps_Confirmed_Arguments_Comments_Reminder {
            get {
                return ResourceManager.GetString("Worksheet.Manual/Steps.Confirmed.Arguments.Comments.Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WorksheetItem_TrackerRunning {
            get {
                return ResourceManager.GetString("WorksheetItem/TrackerRunning", resourceCulture);
            }
        }
    }
}
